# Generated by Django 5.2.14 on 2026-06-01 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('km', models.IntegerField(default=0, verbose_name='Kilometraje')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='FichaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Entrega')),
                ('motivo', models.TextField(verbose_name='Motivo de Ingreso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('diagnostico', 'En Diagnóstico'), ('en_reparacion', 'En Reparación'), ('espera_repuestos', 'Espera de Repuestos'), ('listo', 'Listo para Entrega'), ('entregado', 'Entregado')], default='recibido', max_length=20, verbose_name='Estado')),
                ('km_ingreso', models.IntegerField(default=0, verbose_name='Km al Ingreso')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='fichas.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Ficha de Ingreso',
                'verbose_name_plural': 'Fichas de Ingreso',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
