# Generated by Django 5.2.14 on 2026-06-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='km',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='acc_alfombras',
            field=models.BooleanField(default=False, verbose_name='Alfombras'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='acc_baliza',
            field=models.BooleanField(default=False, verbose_name='Baliza'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='acc_compresor',
            field=models.BooleanField(default=False, verbose_name='Compresor'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='acc_extintor',
            field=models.BooleanField(default=False, verbose_name='Extintor'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='acc_gato',
            field=models.BooleanField(default=False, verbose_name='Gato'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='acc_llave_rueda',
            field=models.BooleanField(default=False, verbose_name='Llave de Rueda'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='acc_rueda_auxilio',
            field=models.BooleanField(default=False, verbose_name='Rueda de Auxilio'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='acc_tuerca_seguridad',
            field=models.BooleanField(default=False, verbose_name='Tuerca de Seguridad'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='chassis',
            field=models.CharField(blank=True, max_length=50, verbose_name='Chassis'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='km_entrada',
            field=models.IntegerField(default=0, verbose_name='Km Entrada'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='km_salida',
            field=models.IntegerField(default=0, verbose_name='Km Salida'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=20, unique=True, verbose_name='Chapa'),
        ),
    ]
