# Generated by Django 5.2.14 on 2026-06-02 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_remove_vehiculo_km_vehiculo_acc_alfombras_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaingreso',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Hoja de Recepción', 'verbose_name_plural': 'Hojas de Recepción'},
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='solicitud',
            field=models.TextField(default='', verbose_name='Solicitud del Cliente'),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso'),
        ),
    ]
