# Generated by Django 5.2.14 on 2026-06-02 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_alter_fichaingreso_options_and_more'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempresupuesto',
            options={'ordering': ['pk'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='itempresupuesto',
            name='precio',
            field=models.BigIntegerField(default=0, verbose_name='Precio (₲)'),
        ),
        migrations.AlterField(
            model_name='itempresupuesto',
            name='descripcion',
            field=models.CharField(max_length=300, verbose_name='Descripción del Trabajo'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='fichas.fichaingreso', verbose_name='Hoja de Recepción'),
        ),
    ]
