# Generated by Django 5.2.14 on 2026-06-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_alter_itempresupuesto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempresupuesto',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='itempresupuesto',
            name='precio',
            field=models.BigIntegerField(default=0, verbose_name='Precio Unitario (₲)'),
        ),
    ]
