# Generated by Django 5.2.14 on 2026-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=30, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Documento de Identidad Nro.'),
        ),
    ]
