# Generated by Django 5.2.14 on 2026-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_ciudad_cliente_ruc_alter_cliente_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='requiere_factura',
            field=models.BooleanField(default=False, verbose_name='Requiere Factura'),
        ),
    ]
